
l=[10,20,30, 40]
a=l.append(50)
print("Append:",l)
i=l.insert(2, 25)
print("insert:",l)
e=l.extend([60, 70])
print("extend:",l)
p=l.pop(2)
print("pop:",l)
r=l.remove(70)
print("remove:",l)
n=l.count(1)
print("count:",l)
x=l.index(30)
print("index:",l)
rev=l.reverse()
print("reverse:",l)
s=l.sort()
print("sort:",l)
c=l.copy()
print("copy:",l)
clear=l.clear()
print("clear:",l)
